# -*- coding: utf-8 -*-
"""01_bus_ticket_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPtaawATMJW0f9rqJBsXUW6i1swYbXm1

#Problem: Smart Bus Ticket Analyzer

A bus company stores passenger travel data like this:

trips = [

    ("Rahul", "Hyderabad", "Vijayawada", 350),

    ("Anu", "Chennai", "Bangalore", 200),

    ("Rahul", "Vijayawada", "Visakhapatnam", 400),

    ("Kiran", "Hyderabad", "Bangalore", 500),

    ("Anu", "Bangalore", "Mysore", 150),

    ("Rahul", "Visakhapatnam", "Kolkata", 800),
]

Each tuple contains:

(passenger_name, source, destination, ticket_price)

data prepared in a list
"""

trips = [
    ("Rahul", "Hyderabad", "Vijayawada", 350),
    ("Anu", "Chennai", "Bangalore", 200),
    ("Rahul", "Vijayawada", "Visakhapatnam", 400),
    ("Kiran", "Hyderabad", "Bangalore", 500),
    ("Anu", "Bangalore", "Mysore", 150),
    ("Rahul", "Visakhapatnam", "Kolkata", 800)
]
# Each tuple contains:
# (passenger_name, source, destination, ticket_price)

# creating list for each one like names , location , destination , ticket price..
names=[]
location=[]
destination=[]
amount=[]
for name , loc , dest , price in trips:
  names.append(name),location.append(loc),destination.append(dest),amount.append(price)
print(names)
print(location)
print(destination)
print(amount)

"""##1. Find Total Amount Spent by Each Passenger"""

amount_spent={}
for i,name in enumerate(names):
  if name in amount_spent:
    amount_spent[name]=amount_spent[name]+amount[i]
  else:
    amount_spent[name]=amount[i]
for name,price in amount_spent.items():
  print(name,price)

"""##2. Find Passenger Who Traveled the Most Times"""

travel_times={}
def most_travel():

  for name in set(names):
    travel_times[name]=names.count(name)
  for n in travel_times:
    if travel_times[n]==max(travel_times.values()):
      print(f'{n} traveled {travel_times[n]} times')
most_travel()
print('travel history :',travel_times)

"""##3. Find the Most Expensive Trip"""

max_amount=max(amount)
for i, price in enumerate(amount):
  if price == max_amount:
    print(f'{names[i]} :{location[i]} -> {destination[i]} : {price}')

"""##4. Find All Unique Cities
[ 'Hyderabad', 'Vijayawada', 'Chennai', 'Bangalore', 'Visakhapatnam', 'Mysore', 'Kolkata' ]
"""

total_cities=[]
all=[]
all.extend((destination))
all.extend((location))
for i in all:
  if i not in total_cities:
    total_cities.append(i)
print(total_cities)

"""#5. Create This Final Report Format

Expected Output:

========= BUS REPORT =========

###Passenger Summary:

Rahul -> Trips: 3 | Amount: 1550

Anu -> Trips: 2 | Amount: 350

Kiran -> Trips: 1 | Amount: 500

###Most Frequent Traveler:

Rahul (3 trips)

###Most Expensive Trip:

Rahul : Visakhapatnam -> Kolkata : 800

###Total Unique Cities:
7
"""

print('========= BUS REPORT =========\n')
print('Passenger Summary:\n')
for name,price in amount_spent.items():
  print(f'{name} -> trips {travel_times[name]} |Amount : {price} ')
print('\nMost Frequent Traveler:')
for tri in travel_times:
  if travel_times[tri]==max(travel_times.values()):
    print(f'{tri}({travel_times[tri]} trips)')
print('\nMost Expensive Trip:')
for i, price in enumerate(amount):
  if price == max(amount):
    print(f'{names[i]} :{location[i]} -> {destination[i]} : {price}')
print(f'\nTotal Unique Cities: {len(total_cities)}')